


<?php $__env->startSection('container'); ?>
<div id="w1" class="tabel" style="user-select:auto ">
    <div style="margin-top: 10% ; margin-left: 10%; margin-right: 10% ">
        <h3 >Info <hr size="6%"></h3>
        <button style= "margin-bottom:10px ;width: 75px; height: 25px; background-color: gray; border-color:antiquewhite ; color: black"><a href="prodi.html">Return</a></button>  
    <table class="table table-striped table-bordered" style="user-select: auto;"><thead style="user-select: auto;">
    <tr style="user-select: auto;"><th style="user-select: auto;">#</th><th style="user-select: auto;">Info</th><th class="action-column" style="user-select: auto;">&nbsp;</th></tr>
    </thead>
    <tbody style="user-select: auto;">
    <tr style="user-select: auto;"><td style="user-select: auto;">1</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto; width: 10px;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">1</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">2</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">3</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">4</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">5</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">6</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">7</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">8</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">9</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">10</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">11</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">12</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">13</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">14</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>
    <tr style="user-select: auto;"><td style="user-select: auto;">15</td><td style="user-select: auto;"><a href=" " style="user-select: auto;"> <b style="user-select: auto;"><font color="#FF0000" style="user-select: auto;">[PPKHA]</font><font color="#008000" style="user-select: auto;">[Campus Hiring]</font><font color="#0000FF" style="user-select: auto;"> PT Dan Liris</font></b></a></td><td class="col-xs-1" style="user-select: auto;"><div class="btn-group" style="user-select: auto;"><button type="reset" style="user-select: auto;">Hapus</button>    </div></td></tr>

    </tbody></table>
    <div class="row" style="user-select: auto;"><div class="col-sm-12 col-md-5" style="user-select: auto;"><div class="dataTables_info" id="datatable1_info" role="status" aria-live="polite" style="user-select: auto;"></div></div><div class="col-sm-12 col-md-7" style="user-select: auto;"><div class="dataTables_paginate paging_simple_numbers" id="datatable1_paginate" style="user-select: auto;"><ul class="pagination" style="user-select: auto;"><li class="paginate_button page-item previous disabled" id="datatable1_previous" style="user-select: auto;"><a href="#" aria-controls="datatable1" data-dt-idx="0" tabindex="0" class="page-link" style="user-select: auto;">Previous</a></li><li class="paginate_button page-item active" style="user-select: auto;"><a href="#" aria-controls="datatable1" data-dt-idx="1" tabindex="0" class="page-link" style="user-select: auto;">1</a></li><li class="paginate_button page-item " style="user-select: auto;"><a href="#" aria-controls="datatable1" data-dt-idx="2" tabindex="0" class="page-link" style="user-select: auto;">2</a></li><li class="paginate_button page-item next" id="datatable1_next" style="user-select: auto;"><a href="#" aria-controls="datatable1" data-dt-idx="3" tabindex="0" class="page-link" style="user-select: auto;">Next</a></li></ul></div></div></div></div>   
   </div> 
</div>

<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.main', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH E:\LARAVEL\kelompok-03\resources\views/info.blade.php ENDPATH**/ ?>